---

- name: Remove amd packages
  become: true
  ansible.builtin.package:
    name: "{{ amd_driver_packages }}"
    state: absent

- name: Remove nvidia driver packages
  become: true
  ansible.builtin.package:
    name: "{{ nvidia_driver_packages[ansible_os_family] }}"
    state: absent
  notify: Reboot Host

- name: Remove unused dependencies
  become: true
  ansible.builtin.package:
    autoremove: true

...
