---

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Debian prerequisites
  when: ansible_distribution == "Debian"
  block:
    - name: Install kernel headers
      become: true
      ansible.builtin.apt:
        name:
          - zstd
          - linux-headers-amd64
        state: present

    - name: Ensure non-free repos are present
      become: true
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/bookworm-main.list
        content: |
          deb http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware
        owner: root
        group: root
        mode: '0644'

    - name: Install kernel headers
      become: true
      ansible.builtin.apt:
        update_cache: true

- name: Install NVIDIA driver
  become: true
  ansible.builtin.apt:
    name: "{{ nvidia_driver_packages[ansible_distribution] }}"
    state: present
  notify: Reboot Host

...
