---

- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install NVIDIA driver Debian
  become: true
  ansible.builtin.apt:
    name: "{{ nvidia_driver_packages[ansible_os_family] }}"
    state: present
  notify: Reboot Host

...
