---

- name: Gather package facts
  ansible.builtin.package_facts:

- name: Verify vendor list
  when: (gpu_vendors | difference(supported_vendors)) | length > 0
  ansible.builtin.fail:
    msg: "Non-supported gpu_vendors found: {{ gpu_vendors | difference(supported_vendors) }}"

- name: Install gpu driver
  loop: "{{ gpu_vendors }}"
  loop_control:
    loop_var: "gpu_vendor"
  ansible.builtin.include_tasks:
    file: "{{ ansible_os_family | lower }}_{{ gpu_vendor | lower }}.yml"

...
